### PR TITLE
Bump govmomi to 0.30.6

### PR DESCRIPTION
**Pull request by lubronzhan**
**What this PR does / why we need it**:
Need govmomi fix https://github.com/vmware/govmomi/issues/3174 for validating certificate's tlsthumbprint to work properly

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/kubernetes/cloud-provider-vsphere/issues/736

**Special notes for your reviewer**:

**Release note**:

```release-note
Bump govmomi to 0.30.6
```

### CODE REVIEW

**Comment by liggitt** [comment]
Does this also need to be updated in kubernetes/kubernetes for go1.20? That is still using v0.30.0 (see https://github.com/kubernetes/kubernetes/pull/114766 and backports)

**Comment by liggitt** [comment]
cc @MadhavJivrajani

**Comment by lubronzhan** [comment]
cc @wyike it should be needed

**Comment by MadhavJivrajani** [comment]
@liggitt I think we'll have to bump and back-port. This issue didn't surface directly in our CI.

We did a similar fix but in our tests: https://github.com/kubernetes/kubernetes/commit/c31cc5ec46315a02343ec6d6a2ef659e2cc8668e
and the reason it worked in our CI was because the function being relies on text matching in the error string.

**Pull request merged**
