### PR TITLE
use string data for example vSphere secret manifest

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

**What this PR does / why we need it**:
Use stringData for secret manifest, easier to install since you don't have to take the extra step of base64 encoding your secret values.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by andrewsykim** [comment]
oops typo

/assign @dvonthenen

**Comment by frapposelli** [comment]
Holding this PR until we define if it's going to make the 0.2.0 cut
/hold

**Comment by dvonthenen** [comment]
@frapposelli yea, plus we didn't make the change on the CSI side for the 0.2.0 release. if we do make this change on the CCM side, the instructions will be different between the two and might be confusing. Currently, they are identical.

**Pull request merged**
