### PR TITLE
Bump K8S and CAPI in e2e test

### LINKED ISSUE #750: Kubernetes 1.28 support
Kubernetes 1.28 will be released next week.

Just wanted to open an issue to be able to follow the work for the cloud-provider-vsphere v1.28 release.

Are there already plans to publish a v1.28 version?

(context: We'll try to bump relatively quickly in Cluster API provider vsphere: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2203)

### PR DESCRIPTION
**Pull request by wyike**
**What this PR does / why we need it**:

A follow up bump K8S PR for e2e against  https://github.com/kubernetes/cloud-provider-vsphere/pull/751. Following suggestion of Stepan (https://github.com/kubernetes/cloud-provider-vsphere/pull/751#issuecomment-1690034548), we pin the otel/metric version to 0.31.0 which make CAPI/controller-runtime/K8S bump successfully.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #750 

**Special notes for your reviewer**:

**Release note**:

```release-note
Bump K8S and CAPI in e2e test
```

### CODE REVIEW

**Comment by wyike** [comment]
cc @lubronzhan @sbueringer

**Comment by sbueringer** [comment]
Was looking into the error.

I think we had the same problem in CAPI. Basically there is no version of helm which uses a oras.land/oras-go dependency that is compatible with what we need in CAPI. In CAPI we got rid of our helm Go dependency

**Comment by sbueringer** [comment]
^^ @lubronzhan @wyike

**Comment by wyike** [comment]
Ah sorry I forgot to run `go test e2e_suite_test.go ` after I did the successful `go mod tidy` locally before pushing the commit.  

Thank you @sbueringer  pointing out the root cause!
I checked the latest helm release, now it's using https://github.com/helm/helm/blob/release-3.12/go.mod#L66 v23.0.1 now but still has 1 incompatibility error out of the original 2 after I locally update helm.

I'll try to work with @lubronzhan  to release 1.28 first and I'll come back to take care of it. The worst thing we have to do is to remove helm go dependency like capz if there is still no newer compatible helm release out at that time.

**Comment by lubronzhan** [comment]
We can release the 1.28 first

**Comment by wyike** [comment]
> Ah sorry I forgot to run `go test e2e_suite_test.go ` after I did the successful `go mod tidy` locally before pushing the commit.
> 
> Thank you @sbueringer pointing out the root cause! I checked the latest helm release, now it's using https://github.com/helm/helm/blob/release-3.12/go.mod#L66 v23.0.1 now but still has 1 incompatibility error out of the original 2 after I locally update helm.
> 
> I'll try to work with @lubronzhan to release 1.28 first and I'll come back to take care of it. The worst thing we have to do is to remove helm go dependency like capz if there is still no newer compatible helm release out at that time.

Very lucky, the helm latest 3.13.1 release bumped oras.land/oras-go https://github.com/helm/helm/blob/v3.13.1/go.mod#L47 and docker/docker is bumped to 24.0.6 https://github.com/helm/helm/blob/v3.13.1/go.mod#L69 as a result.

I bumped helm to v3.1.3.1 in this PR.

**Comment by sbueringer** [comment]
Interesting. Looks like a race condition and it merged regardless of the label :)

**Pull request merged**
