### PR TITLE
Remove CSI code from repo

### LINKED ISSUE #170: Explore splitting CSI plugin into separate repo
/kind cleanup

We should look at whether we want to move the CSI plugin to it's own separate repo. Having it in the same repo as the CCM means they are coupled for releases, and makes versioning and tagging more complicated. We originally put CSI in here with the CCM because we followed [KEP 02](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20180530-cloud-controller-manager.md#repository-requirements), but this is worth a revisit. Early discussions with @andrewsykim indicate SIG-cloud provider may be open to changing this.

Assuming we *do* want to split out, two questions arise:

What is the location for the new repo? k8s-sigs has been the most common suggestion so far.

Since the CSI repo will need to import the common code from the CCM, should we move the commong code (e.g. `cloud-provider-vsphere/pkg/common`) to a separate repo as well? This would likely need to be hosted under the VMware org rather than Kubernetes.

### PR DESCRIPTION
**Pull request by codenrhoden**
**What this PR does / why we need it**:
The CSI implementation has been moved to a different repo, and is no
longer needed here. A note has been added to the README for its new
location.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #170 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

/hold

Will cancel hold once new repo is populated fully.

### CODE REVIEW

**Comment by codenrhoden** [comment]
/hold cancel

new repo has been populated

**Comment by frapposelli** [comment]
/lgtm

@akutz PTAL, just want to make sure we're ok with the prow jobs

**Comment by codenrhoden** [comment]
> /lgtm However, I'm only reviewing the changes. There could be mentions that have not been removed. Have you tried building it using the CI image?

I have. Works as expected.

```sh
[trhoden@mbp ~/git/k8s.io/cloud-provider-vsphere (remove-csi)]$ make build-with-docker
hack/make.sh
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static" -w -s -X "main.version=51a0f0c9"' -o /build/.build/bin/vsphere-cloud-controller-manager.linux_amd64 cmd/vsphere-cloud-controller-manager/main.go
[trhoden@mbp ~/git/k8s.io/cloud-provider-vsphere (remove-csi)]$
```

**Comment by codenrhoden** [comment]
@fabio how are you feeling about this now?

**Comment by frapposelli** [comment]
🐑 🇮🇹 

/approve

**Pull request merged**
