### PR TITLE
Add descriptive instanceType to nodes

### PR DESCRIPTION
**Pull request by frapposelli**
**What this PR does / why we need it**:

This PR adds support for returning a more descriptive InstanceType for nodes, instead of returning a static string.

**Which issue this PR fixes** 

Fixes: #55

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by frapposelli** [comment]
thanks @dvonthenen not ready for merge yet

**Comment by dvonthenen** [comment]
Just kidding... just sat down with my coffee.  😀

**Comment by frapposelli** [comment]
Now it's ready 😄 

Tested on my local cluster:
```console
root@kube-fabio-1:~# kubectl get nodes --show-labels
NAME           STATUS   ROLES    AGE     VERSION   LABELS
kube-fabio-1   Ready    master   2m47s   v1.13.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=vsphere-vm.cpu-2.mem-8gb.os-ubuntu,beta.kubernetes.io/os=linux,kubernetes.io/hostname=kube-fabio-1,node-role.kubernetes.io/master=
kube-fabio-2   Ready    <none>   2m25s   v1.13.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=vsphere-vm.cpu-2.mem-8gb.os-ubuntu,beta.kubernetes.io/os=linux,kubernetes.io/hostname=kube-fabio-2
kube-fabio-3   Ready    <none>   2m25s   v1.13.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=vsphere-vm.cpu-2.mem-8gb.os-ubuntu,beta.kubernetes.io/os=linux,kubernetes.io/hostname=kube-fabio-3
```

**Comment by frapposelli** [comment]
thanks Doug!

**Comment by frapposelli** [comment]
@dougm btw, the hash table I added is to map the guest identifier with a shorthand of our choice, as it needs to be short and without special char to match the pattern

`vsphere-vm.cpu-<cpu number>.mem-<mem in gb>gb.os-<os shorthand>`

I tried to use the OS description directly but it was too long and verbose, like 

`vsphere-vm.cpu-2.mem-8gb.os-Ubuntu Linux`

**Pull request merged**
