### PR TITLE
Revert k8s.io/kubernetes to 1.18.12

### PR DESCRIPTION
**Pull request by nicolehanjing**
**What this PR does / why we need it**:
bumped to v1.19.3 prior to cutting the official v1.18 release
we need to revert that to the latest v1.18 patch release and bump it back to v1.19 once we cut v1.18.0

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Reverted unimplemented InstancesV2() since that change was introduced after bumping to v1.19.3

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nicolehanjing** [comment]
/assign @andrewsykim 
did manual tests on my TKG cluster and it worked well
Reverted unimplemented InstancesV2() since that change was introduced after bumping to v1.19.3

**Comment by dvonthenen** [comment]
@nicolehanjing I think we are cutting the 1.18 releases from the 1.18 branch (https://github.com/kubernetes/cloud-provider-vsphere/tree/release-1.18) going forward

**Comment by andrewsykim** [comment]
@dvonthenen I had asked @nicolehanjing to revert go mods back to v1.18 because I think there are some features / bug fixes we're going to want to add prior to cutting v1.18 and I don't think we want to cherry-pick all of those into a v1.18 branch. My fault for jumping the gun early and updating the go moduels to v1.19. 

For future versions, we shouldn't bump the go mod version until we've cut the official tag of the previous version. So I think we should bump this back to v1.19 once we've cut v1.18.0

**Comment by dvonthenen** [comment]
makes sense... no worries then. yea, the branching thing is definitely going to add some overhead going forward.

**Comment by andrewsykim** [comment]
> makes sense... no worries then. yea, the branching thing is definitely going to add some overhead going forward.

Agreed, it's gonna take some time for us to adapt to the new release cadence.

**Pull request merged**
