### PR TITLE
Fix a batch of typos

### PR DESCRIPTION
**Pull request by mooncak**
**What this PR does / why we need it**:
Fix typos: attachs -> attaches

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by frapposelli** [comment]
@mooncak thanks for this PR, can you please coalesce all the changes you're planning to make in a single PR/commit? this would help with the management burden 👍 .

**Comment by mooncak** [comment]
> @mooncak thanks for this PR, can you please coalesce all the changes you're planning to make in a single PR/commit? this would help with the management burden 👍 .

ok

**Comment by mooncak** [comment]
@frapposelli  after checked all the issue, I have committed.

**Comment by frapposelli** [comment]
Thanks @mooncak 👍 🎉

**Pull request merged**
