### PR TITLE
Use openvpn from community-owned registry

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold

I'll verify it in CAPV virst

**Comment by sbueringer** [comment]
/hold cancel

If CI is green we're good

**Comment by sbueringer** [comment]
/assign @lubronzhan @wyike @DanielXiao 

Please backport to all branches for which you still want to run e2e tests

**Comment by sbueringer** [comment]
/assign @lubronzhan @wyike 

(for approval)

**Comment by DanielXiao** [comment]
@XudongLiuHarold Could you approve this PR?

**Comment by lubronzhan** [comment]
/lgtm
/approve
Thanks for the change!

**Comment by sbueringer** [comment]
@DanielXiao @lubronzhan If I see correctly we're only running jobs for 1.29-1.27 now. Please cherry-pick back further if necessary :)

**Pull request merged**
