### PR TITLE
Add dependabot so package could be bumped automatically

### PR DESCRIPTION
**Pull request by lubronzhan**
**What this PR does / why we need it**:
Add dependabot so package could be bumped automatically
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add dependabot so package could be bumped automatically
```

### CODE REVIEW

**Comment by lubronzhan** [comment]
cc @wyike @YanzhaoLi

**Comment by YanzhaoLi** [comment]
The labels are ok-to-test. Those configuration can be validated after merging. 
/lgtm

**Comment by wyike** [comment]
It'll auto-bump k8s.io related packages?

**Comment by YanzhaoLi** [comment]
> It'll auto-bump k8s.io related packages?

I think it'll auto-bump all kinds of packages defined under the `package-ecosystem` and generate corresponding MR with ok-to-test label.  Concurrent k8s.io related packages update can be combined in one MR.

**Pull request merged**
