### PR TITLE
Generate vm-operator-api clientset code

### PR DESCRIPTION
**Pull request by XudongLiuHarold**
**What this PR does / why we need it**:

- Generate vmoperator-api's  clientset code
- We need this clientset code to replace `controller-runtime` package's client

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wyike** [comment]
Curious what the vm-operator api repo is? They didn't have these apis defined?

**Comment by XudongLiuHarold** [comment]
> Curious what the vm-operator api repo is? They didn't have these apis defined?

The repo has been achieved: https://github.com/vmware-archive/vm-operator-api, we need to migrate to new one here: https://github.com/vmware-tanzu/vm-operator in a follow-up PR.

**Comment by wyike** [comment]
> > Curious what the vm-operator api repo is? They didn't have these apis defined?
> 
> @wyike : The repo has been achieved: https://github.com/vmware-archive/vm-operator-api, we need to migrate to new one here: https://github.com/vmware-tanzu/vm-operator in a follow-up PR.

Should we use this submodule https://github.com/vmware-tanzu/vm-operator/tree/main/api instead of generating/maintaining ourselves? cc @lubronzhan

**Comment by XudongLiuHarold** [comment]
> > > Curious what the vm-operator api repo is? They didn't have these apis defined?
> > 
> > 
> > @wyike : The repo has been achieved: https://github.com/vmware-archive/vm-operator-api, we need to migrate to new one here: https://github.com/vmware-tanzu/vm-operator in a follow-up PR.
> 
> Should we import and use this submodule https://github.com/vmware-tanzu/vm-operator/tree/main/api instead of generating/maintaining ourselves? cc @lubronzhan

@wyike , even in that repo, it doesn't contain generated vmop clientset

**Comment by wyike** [comment]
> > > > Curious what the vm-operator api repo is? They didn't have these apis defined?
> > > 
> > > 
> > > @wyike : The repo has been achieved: https://github.com/vmware-archive/vm-operator-api, we need to migrate to new one here: https://github.com/vmware-tanzu/vm-operator in a follow-up PR.
> > 
> > 
> > Should we import and use this submodule https://github.com/vmware-tanzu/vm-operator/tree/main/api instead of generating/maintaining ourselves? cc @lubronzhan
> 
> @wyike , even in that repo, it doesn't contain generated vmop clientset yet

They should add it per our asks.

**Pull request closed without merging**
