### PR TITLE
Bump cloud-provider-vsphere to k8s v1.25

### PR DESCRIPTION
**Pull request by lobziik**
**What this PR does / why we need it**:
Updated k8s libs to v1.25, then ran:
go mod tidy

Also bump go version to 1.18

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Bump cloud-provider-vsphere to k8s v1.25
Update minimum required golang version to 1.18
```

### CODE REVIEW

**Comment by lobziik** [comment]
/cc @lubronzhan

Can you please take a look? :)

**Comment by lubronzhan** [comment]
Thanks for the PR! Sorry I was on PTO
Noticed that upstream is using golang 1.19 now https://github.com/kubernetes/cloud-provider/blob/release-1.25/go.mod
I'll try create a follow up PR to bump it to 1.19
/lgtm
/approve

**Comment by divyenpatel** [comment]
@lubronzhan @lobziik 
When can we have a release available for the k8s 1.25?

**Comment by lobziik** [comment]
@divyenpatel would be good to merge this https://github.com/kubernetes/cloud-provider-vsphere/pull/659 first...

**Pull request merged**
