### PR TITLE
Update docs to include images and help clarify certain scenarios for zones

### PR DESCRIPTION
**Pull request by dvonthenen**
**What this PR does / why we need it**:
Just like the title says... docs now include images to help clarify how zones work as they relate to placement and storage. Also added a section to give an example of what not to do in the section called "Pitfalls".

Will be making a duplicate of this doc in the vSphere CSI driver repo after I get feedback for updates and it gets merged.

**Which issue this PR fixes**:
NA

**Special notes for your reviewer**:
NA

**Release note**:
NA

### CODE REVIEW

**Comment by dvonthenen** [comment]
CC: @frapposelli @codenrhoden @andrewsykim

**Comment by andrewsykim** [comment]
LGTM

**Pull request merged**
