### PR TITLE
[release-1.23] CI: move to new resource pool and folder in VMC and migrate to new IPAM

### PR DESCRIPTION
**Pull request by chrischdi**
This is a manual cherry-pick of https://github.com/kubernetes/cloud-provider-vsphere/pull/763

This also cherry-picks a change in `hack/release.sh` required to make the branch succeed.

### CODE REVIEW

**Comment by chrischdi** [comment]
/retest

propably flake

**Comment by lubronzhan** [comment]
/lgtm
/approve
Thanks for the change!

**Pull request merged**
