### PR TITLE
Fix staticcheck error by cluster-api dependency.

### PR DESCRIPTION
**Pull request by HanFa**
**What this PR does / why we need it**:

Bump CAPI version from 1.0.2 to v1.1.0-beta.1

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix staticcheck error by cluster-api dependency.
```

### CODE REVIEW

**Comment by lubronzhan** [comment]
I see `capi` version used to be `0.4.5`? Will 1.0.2 has the same issue? I saw

**Comment by HanFa** [comment]
> 

yes, any CAPI version under v1.1.0-beta.1 will have this issue as it uses different version of logr from upstream.

**Pull request merged**
