### PR TITLE
when nodes have multiple NICs, we need to go through all listed items before returning error

### PR DESCRIPTION
**Pull request by dpengla**
**What this PR does / why we need it**:
This PR cherry-picks  a04551953ec1c854358f5bad1ab4ce10f06818c3. ce85bea3cb39de7e2aedd485e9caca42706e24d3 and 649912ca4e9d340ee7d3c6ae35873ef5fb0997cd from release-1.19 and adds them to master.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes: https://github.com/kubernetes/cloud-provider-vsphere/issues/450

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by andrewsykim** [comment]
I didn't realize the original PR was for release-1.19 and not master, next time please merge the fix into master first and then do the cherry-pick

**Comment by andrewsykim** [comment]
Also, please squash the last two commits

**Comment by dpengla** [comment]
Sure. Thanks!

**Pull request merged**
