### PR TITLE
Update versions to latest

### PR DESCRIPTION
**Pull request by briantopping**
**What this PR does / why we need it**:
https://github.com/vmware/vsphere-automation-sdk-go/releases/tag/services%2Fnsxt%2Fv0.9.0 has been a thing since 2022-Jul. This PR brings in the changes along with general upgrades to the rest of libraries and the base Golang image to v1.20.2. 

**Release note**:

```
Upgrade libraries including github.com/vmware/vsphere-automation-sdk-go, builder Golang image to v1.20.2, Distroless base image from Debian 9 to 11.
```

### CODE REVIEW

**Comment by briantopping** [comment]
Note that this PR updates the base image from Debian 9.9, which has been EOL for almost three years now.

**Comment by lubronzhan** [comment]
Thanks for the PR!
/ok-to-test

**Comment by lubronzhan** [comment]
Hi @briantopping take care!
I asked around turns out the infra did a maintenance on the server and updated TLSThumbprint of VC. But somehow Prow job is not consuming the newest TLSThumbprint. 
Workaround would be hardcode the Thumbprint in our test config instead of inside Prow server.
Let me hardcode the TLSThumprint on master branch to unblock you then

**Comment by briantopping** [comment]
Thanks @lubronzhan! Hopefully back to normal soon, but I'm sure this would have taken some time to find as my first work with the e2e.

You also have edit privs on the branch if you just want to work from there. If not, I will rebase to master once you have the change in place. :)

**Comment by lubronzhan** [comment]
Hi @briantopping the fix was merged. Could you please rebase?

**Comment by briantopping** [comment]
@lubronzhan looks like that worked! Thanks for your prompt help!! 👍

**Comment by briantopping** [comment]
Hi @lubronzhan, any chance you'd be cutting a release with these version changes soon? I need to cut a release on a dependent and it would be great to clear out these CVE nags from our internal compliance tools...
image

**Comment by lubronzhan** [comment]
Hi @briantopping let me try find some time to cut release in next two weeks. Thanks for reminding

**Comment by lubronzhan** [comment]
Hi @briantopping when cherry pick, I'll keep the sdk change and distroless image bump, but leave out the golang version bump since we want to keep the same as what k8s use

**Comment by briantopping** [comment]
Hi @lubronzhan, happy Friday!

My advice is to not do that without specific incompatibility reasons – reasons that would rise to a rather epic set of issues in k8s and/or Golang. The goal of Kubernetes containers operating over gRPC is that the compatibility is locked to specific object API versions, not the generation of thereof. This allows the underlying implementation of the foundation to evolve as quickly as necessary. 

The local problem of not upgrading to the latest is this project does not release often enough to keep up with the CVE train that Golang drives as it is. 

Would it help if I provide a list of current critical CVEs against Golang 1.19?

**Comment by lubronzhan** [comment]
Hi @briantopping don't worry, the newest golang 1.19 has the same CVE fixes as 1.20.3
https://go.dev/doc/devel/release

**Comment by briantopping** [comment]
Hi @lubronzhan, FYI https://github.com/kubernetes/cloud-provider-vsphere/commit/69dbf1313019d4785c7003c6edfa04c84f653e26#commitcomment-111368927

**Pull request merged**
