### PR TITLE
Release 1.31.1

### PR DESCRIPTION
**Pull request by lubronzhan**
**What this PR does / why we need it**:
Release 1.31.1

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
To include this https://github.com/kubernetes/cloud-provider-vsphere/pull/1285

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by lubronzhan** [comment]
Gonna create release note and push a tag once this is merged

**Comment by XudongLiuHarold** [comment]
/lgtm

will discuss on the release version and release plan

**Comment by XudongLiuHarold** [comment]
Talked with @DanielXiao , we can merge this and release `v1.31.1`

/hold cancel

**Pull request merged**
