### PR TITLE
fix/typo: removed typo in line 5

### PR DESCRIPTION
**Pull request by lukibahr**
**What this PR does / why we need it**:

simply a typo in the docs

### CODE REVIEW

**Comment by dvonthenen** [comment]
@lukibahr could you please sign the CLA? and then we can merge 😀

Info:
https://identity.linuxfoundation.org/projects/cncf

**Comment by lukibahr** [comment]
@dvonthenen just signed the CLA.

**Comment by dvonthenen** [comment]
retest

**Comment by dvonthenen** [comment]
Tried fixing the other errors through a retest, but it doesn't seem to clear the non-relevant CI tests. Just going to merge this.

/approve
/lgtm

**Pull request merged**
