### PR TITLE
update e2e test dependency to 1.30

### PR DESCRIPTION
**Pull request by XudongLiuHarold**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
looks like this one https://github.com/kubernetes/cloud-provider-vsphere/pull/1034 are quite similar! lmk if you want to take this bump @XudongLiuHarold

**Comment by XudongLiuHarold** [comment]
> looks like this one #1034 are quite similar! lmk if you want to take this bump @XudongLiuHarold

Hey @sunjayBhatia , thanks!

We are working on removing the annoying helm dependency here: https://github.com/kubernetes/cloud-provider-vsphere/pull/1046, I guess we can make some progress on this one once that one merged.

**Pull request closed without merging**
