### PR TITLE
Add cli tests for vcpctl

### PR DESCRIPTION
**Pull request by fanzhangio**
Add unit tests for client and user 
Issue #47 

To run these tests, VC_TEST env should be set up
```
export VC_TEST_URL=<VC URL>
export VC_TEST_PASSWORD=<VC password>
export VC_TEST_USERNAME=<VC username>
```
@dougm @frapposelli

### CODE REVIEW

**Comment by frapposelli** [comment]
Are these tests running with `make test`?

**Comment by frapposelli** [comment]
@fanzhangio can you test against `vcsim`?

**Comment by frapposelli** [comment]
/retest

looks like there's something wrong with the infra

**Comment by fanzhangio** [comment]
According to the test log, `FAIL: TestRegUnregNode` failed in `nodemanager_test.go`

**Comment by fanzhangio** [comment]
@akutz Could you please take a look at this ?

**Pull request merged**
