### PR TITLE
Switch from using glog to klog

### PR DESCRIPTION
**Pull request by dvonthenen**
**What this PR does / why we need it**:
The kubernetes community is moving away from glog to klog. This updates all components (CCM, CSI, CLI) used to klog.

**Which issue this PR fixes**:
https://github.com/kubernetes/cloud-provider-vsphere/issues/137

**Special notes for your reviewer**:
Tested CCM and CSI on:
- k8s 1.13.1 cluster with 10 worker nodes in 3 zones
- vSphere 6.7u1

**Release note**:
Internal package change

### CODE REVIEW

**Comment by dvonthenen** [comment]
CC: @fabio @dougm @codenrhoden

**Comment by codenrhoden** [comment]
Looks good to me. My only question is why `glog` still shows up as a dependency in `Gopkg.lock`

**Comment by dvonthenen** [comment]
klog is version 0.2.0 and glog is still present because there are subcomponents that depend on it. I read the klog docs… glog and klog can co-exist in the same project (and be vendored in together). I verify that we see log lines originating from both glog and klog.

**Pull request merged**
