### PR TITLE
Add additional members to maintainers alias

### PR DESCRIPTION
**Pull request by sunjayBhatia**
**What this PR does / why we need it**:

These additional members will primarily review dependency updates on the master and release branches and help with expediting cutting releases.

These contributors have primarily been involved with this project in a downstream capacity but hope to increase upstream involvement.

**Which issue this PR fixes**

N/A

**Special notes for your reviewer**:

N/A

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by skriss** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://git.k8s.io/community/community-membership.md#member) of the kubernetes org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * skriss
>   
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

Opened kubernetes org membership request: https://github.com/kubernetes/org/issues/4878

**Review by lubronzhan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
