### PR TITLE
Typo fix for vcpctl provision long description

### PR DESCRIPTION
**Pull request by c3y1huang**
**What this PR does / why we need it**:
Typo fix for vcpctl provision long description.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by c3y1huang** [comment]
ref: https://github.com/SUSE/avant-garde/issues/1375

**Comment by dvonthenen** [comment]
It appears that the pull-cloud-provider-vsphere-integration-test failure seems to be with the test itself from possibly it getting stale or with some infrastructure related issue

**Comment by dvonthenen** [comment]
> /test pull-cloud-provider-vsphere-integration-test

Yea, going to need to take a look at it... it seems it just up and broke without any reason

**Pull request merged**
