### PR TITLE
test/e2e: Bump k8s 0.30.1

### PR DESCRIPTION
**Pull request by sunjayBhatia**
**What this PR does / why we need it**:

Fixes issues with dependabot PRs: https://github.com/kubernetes/cloud-provider-vsphere/pull/1035 and https://github.com/kubernetes/cloud-provider-vsphere/pull/1048

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
again hit by the cluster-api/controller-runtime incompatibility

controller-runtime needs to be bumped with the k8s lib bump but then so does cluster-api to main

**Comment by XudongLiuHarold** [comment]
> /cc @XudongLiuHarold

Thanks @sunjayBhatia !

I have one concern is that if we bump to the latest main, the `dependentbot` will be confused about the version and it will keep submitting PRs to bump dependency to the latest stable version like this one:  https://github.com/kubernetes/cloud-provider-vsphere/pull/1054

So I am not sure if we should bump to the latest main or we should wait for CAPI to release the version that supports k8s 1.30, what do you think about this?

**Comment by sunjayBhatia** [comment]
> > /cc @XudongLiuHarold
> 
> Thanks @sunjayBhatia !
> 
> I have one concern is that if we bump to the latest main, the `dependentbot` will be confused about the version and it will keep submitting PRs to bump dependency to the latest stable version like this one: #1054
> 
> So I am not sure if we should bump to the latest main or we should wait for CAPI to release the version that supports k8s 1.30, what do you think about this?

we should be able to tell dependabot to stop sending PRs for a dependency with the command `@dependabot ignore this dependency` (or `ignore this minor version` etc.) wait for a release and then reenable dependabot (or just ignore/close dependabot PRs manually for the CAPI library) or delay this until we get a CAPI release

I'm slightly in favor of getting the changes in sooner so things don't get more stale, but could go with any of the above

**Comment by XudongLiuHarold** [comment]
> > > /cc @XudongLiuHarold
> > 
> > 
> > Thanks @sunjayBhatia !
> > I have one concern is that if we bump to the latest main, the `dependentbot` will be confused about the version and it will keep submitting PRs to bump dependency to the latest stable version like this one: #1054
> > So I am not sure if we should bump to the latest main or we should wait for CAPI to release the version that supports k8s 1.30, what do you think about this?
> 
> we should be able to tell dependabot to stop sending PRs for a dependency with the command `@dependabot ignore this dependency` (or `ignore this minor version` etc.) wait for a release and then reenable dependabot (or just ignore/close dependabot PRs manually for the CAPI library) or delay this until we get a CAPI release
> 
> I'm slightly in favor of getting the changes in sooner so things don't get more stale, but could go with any of the above

Thanks @sunjayBhatia , make sense!

/lgtm

**Pull request merged**
