### PR TITLE
Add e2e integration tests using vcSim and Kind

### PR DESCRIPTION
**Pull request by akutz**
**What this PR does / why we need it**:
This patch adds e2e integration tests that load the CCM image into a Kubernetes cluster turned up with Kind and the vCenter simulator. Execute the tests with:

```shell
$ make -C test/integration
```

The tests depend on the following binaries locally: `kind`, `kubectl`, and `docker`. Kind may be installed with `go get -u sigs.k8s.io/kind`.

Many thanks to @BenTheElder, @andrewsykim, @munnerz, and @neolit123.

**TODO**:
* Migrate all the shell logic into an actual Ginkgo-based Go test using Kind's golang library
* Refactor the test and the project to use Bazel for caching
* Have better checks than printing the CCM log at the end
* Add a README to the root of the `test` directory and perhaps the `integration` directory as well with documentation on how everything works. For now this PR and the default targets of the Makefiles will serve as the documentation.
* This PR is loosely related to https://github.com/kubernetes/kubernetes/pull/75229. Please note this PR doesn't tell Kind to configure nodes with `--cloud-provider=external`. This is because Kind's CNI plug-in, Weave, won't start properly if the kubelet cannot report the node address. Therefore the cluster is turned up with no cloud provider configured and then the cloud provider taint is manually applied. Whether this solution is long-term is yet to be decided.

**Example Test Run**
```shell
$ make -C test/integration
make build-ccm-image
make[1]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
GOOS=linux make -C ../.. image-controller-manager
make[2]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere'
make[3]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere'
dep ensure -v && touch vendor
make[3]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere'
CGO_ENABLED=0 GOOS=linux go build \
	-ldflags "-w -s -X 'main.version=a0a42c15'" \
	-o vsphere-cloud-controller-manager \
	cmd/vsphere-cloud-controller-manager/main.go
cp vsphere-cloud-controller-manager cluster/images/controller-manager
docker build -t gcr.io/cloud-provider-vsphere/vsphere-cloud-controller-manager:a0a42c15 cluster/images/controller-manager
Sending build context to Docker daemon  54.31MB
Step 1/3 : FROM photon:2.0
 ---> 37c525935c86
Step 2/3 : ADD vsphere-cloud-controller-manager /bin/
 ---> f9d6d95bd6dc
Step 3/3 : CMD ["/bin/vsphere-cloud-controller-manager"]
 ---> Running in 9f62eb9dccd9
Removing intermediate container 9f62eb9dccd9
 ---> 6a4cb71b8042
Successfully built 6a4cb71b8042
Successfully tagged gcr.io/cloud-provider-vsphere/vsphere-cloud-controller-manager:a0a42c15
docker tag gcr.io/cloud-provider-vsphere/vsphere-cloud-controller-manager:a0a42c15 gcr.io/cloud-provider-vsphere/vsphere-cloud-controller-manager:latest
rm cluster/images/controller-manager/vsphere-cloud-controller-manager
make[2]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere'
make[1]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make cluster-up
make[1]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
kind create cluster --config "kind-config.yaml" --name "ccm-integration-test"
Creating cluster "ccm-integration-test" ...
 ✓ Ensuring node image (kindest/node:v1.13.3) 🖼
 ✓ [control-plane] Creating node container 📦 
 ✓ [control-plane] Fixing mounts 🗻 
 ✓ [control-plane] Configuring proxy 🐋
 ✓ [control-plane] Starting systemd 🖥 
 ✓ [control-plane] Waiting for docker to be ready 🐋 
 ✓ [control-plane] Pre-loading images 🐋 
 ✓ [worker] Creating node container 📦 
 ✓ [worker] Fixing mounts 🗻 
 ✓ [worker] Configuring proxy 🐋
 ✓ [worker] Starting systemd 🖥 
 ✓ [worker] Waiting for docker to be ready 🐋 
 ✓ [worker] Pre-loading images 🐋 
 ✓ [control-plane] Creating the kubeadm config file ⛵ 
 ✓ [control-plane] Starting Kubernetes (this may take a minute) ☸ 
 ✓ [worker] Joining worker node to Kubernetes ☸ 
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="ccm-integration-test")"
kubectl cluster-info
make[1]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make load-ccm-image
make[1]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
kind load docker-image --name "ccm-integration-test" gcr.io/cloud-provider-vsphere/vsphere-cloud-controller-manager:a0a42c15
make[1]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make deploy-vcsim
make[1]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
export KUBECONFIG="$(kind get kubeconfig-path --name "ccm-integration-test")" && \
kubectl -n kube-system apply -f ../vcsim/deployment.yaml
serviceaccount/vcsim created
statefulset.apps/vcsim created
service/vcsim created
make[1]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make create-vms
make[1]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
./create-vms.sh "ccm-integration-test"
waiting for vcsim.......................................ok
creating vcsim vm:
  name=ccm-integration-test-control-plane
  fqdn=ccm-integration-test-control-plane
  ipv4=172.17.0.2
   mac=02:42:ac:11:00:02
  uuid=04f419fe-8688-4066-a16d-cbc4193d5b93
  suid=fe19f404-8886-6640-a16d-cbc4193d5b93
creating vcsim vm:
  name=ccm-integration-test-worker
  fqdn=ccm-integration-test-worker
  ipv4=172.17.0.3
   mac=02:42:ac:11:00:03
  uuid=04f419fe-8688-4066-a16d-cbc4193d5b94
  suid=fe19f404-8886-6640-a16d-cbc4193d5b94
make[1]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make deploy-ccm
make[1]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
export KUBECONFIG="$(kind get kubeconfig-path --name "ccm-integration-test")" && \
kubectl -n kube-system create configmap cloud-config --from-file=vsphere.conf && \
kubectl -n kube-system create -f secrets.yaml && \
kubectl -n kube-system apply -f ../../manifests/controller-manager/cloud-controller-manager-roles.yaml && \
kubectl -n kube-system apply -f ../../manifests/controller-manager/cloud-controller-manager-role-bindings.yaml && \
sed 's~gcr.io/cloud-provider-vsphere/vsphere-cloud-controller-manager:latest~gcr.io/cloud-provider-vsphere/vsphere-cloud-controller-manager:a0a42c15~g' <../../manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml | kubectl -n kube-system apply -f -
configmap/cloud-config created
secret/vccm created
clusterrole.rbac.authorization.k8s.io/system:cloud-controller-manager created
clusterrolebinding.rbac.authorization.k8s.io/system:cloud-controller-manager created
serviceaccount/cloud-controller-manager created
pod/vsphere-cloud-controller-manager created
service/vsphere-cloud-controller-manager created
make[1]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make taint-nodes
make[1]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
export KUBECONFIG="$(kind get kubeconfig-path --name "ccm-integration-test")" && \
for name in $(kubectl get nodes -o jsonpath='{.items[*].metadata.name}'); do \
  kubectl taint nodes "${name}" node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule; \
done
node/ccm-integration-test-control-plane tainted
node/ccm-integration-test-worker tainted
make[1]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make log-ccm
make[1]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
export KUBECONFIG=$(kind get kubeconfig-path --name "ccm-integration-test") && \
while ! kubectl -n kube-system logs vsphere-cloud-controller-manager >/dev/null 2>&1; do sleep 1; done && \
sleep 3 && \
kubectl -n kube-system logs vsphere-cloud-controller-manager
I0309 00:48:36.584904       1 flags.go:27] FLAG: --address="0.0.0.0"
I0309 00:48:36.584988       1 flags.go:27] FLAG: --allocate-node-cidrs="false"
I0309 00:48:36.585010       1 flags.go:27] FLAG: --allow-untagged-cloud="false"
I0309 00:48:36.585031       1 flags.go:27] FLAG: --alsologtostderr="false"
I0309 00:48:36.585053       1 flags.go:27] FLAG: --bind-address="0.0.0.0"
I0309 00:48:36.585095       1 flags.go:27] FLAG: --cert-dir="/var/run/kubernetes"
I0309 00:48:36.585110       1 flags.go:27] FLAG: --cidr-allocator-type="RangeAllocator"
I0309 00:48:36.585161       1 flags.go:27] FLAG: --cloud-config="/etc/cloud/vsphere.conf"
I0309 00:48:36.585182       1 flags.go:27] FLAG: --cloud-provider="vsphere"
I0309 00:48:36.585202       1 flags.go:27] FLAG: --cluster-cidr=""
I0309 00:48:36.585223       1 flags.go:27] FLAG: --cluster-name="kubernetes"
I0309 00:48:36.585243       1 flags.go:27] FLAG: --concurrent-service-syncs="1"
I0309 00:48:36.585265       1 flags.go:27] FLAG: --configure-cloud-routes="true"
I0309 00:48:36.585281       1 flags.go:27] FLAG: --contention-profiling="false"
I0309 00:48:36.585301       1 flags.go:27] FLAG: --controller-start-interval="0s"
I0309 00:48:36.585324       1 flags.go:27] FLAG: --feature-gates=""
I0309 00:48:36.585357       1 flags.go:27] FLAG: --help="false"
I0309 00:48:36.585382       1 flags.go:27] FLAG: --http2-max-streams-per-connection="0"
I0309 00:48:36.585403       1 flags.go:27] FLAG: --kube-api-burst="30"
I0309 00:48:36.585424       1 flags.go:27] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0309 00:48:36.585635       1 flags.go:27] FLAG: --kube-api-qps="20"
I0309 00:48:36.585669       1 flags.go:27] FLAG: --kubeconfig=""
I0309 00:48:36.585723       1 flags.go:27] FLAG: --leader-elect="true"
I0309 00:48:36.585755       1 flags.go:27] FLAG: --leader-elect-lease-duration="15s"
I0309 00:48:36.585830       1 flags.go:27] FLAG: --leader-elect-renew-deadline="10s"
I0309 00:48:36.585852       1 flags.go:27] FLAG: --leader-elect-resource-lock="endpoints"
I0309 00:48:36.585907       1 flags.go:27] FLAG: --leader-elect-retry-period="2s"
I0309 00:48:36.585945       1 flags.go:27] FLAG: --log-backtrace-at=":0"
I0309 00:48:36.585968       1 flags.go:27] FLAG: --log-dir=""
I0309 00:48:36.585984       1 flags.go:27] FLAG: --log-flush-frequency="5s"
I0309 00:48:36.586005       1 flags.go:27] FLAG: --logtostderr="true"
I0309 00:48:36.586020       1 flags.go:27] FLAG: --master=""
I0309 00:48:36.586047       1 flags.go:27] FLAG: --min-resync-period="12h0m0s"
I0309 00:48:36.586065       1 flags.go:27] FLAG: --node-monitor-period="5s"
I0309 00:48:36.586115       1 flags.go:27] FLAG: --node-status-update-frequency="5m0s"
I0309 00:48:36.586137       1 flags.go:27] FLAG: --node-sync-period="0s"
I0309 00:48:36.586151       1 flags.go:27] FLAG: --port="10253"
I0309 00:48:36.586173       1 flags.go:27] FLAG: --profiling="false"
I0309 00:48:36.586201       1 flags.go:27] FLAG: --route-reconciliation-period="10s"
I0309 00:48:36.586222       1 flags.go:27] FLAG: --secure-port="0"
I0309 00:48:36.586264       1 flags.go:27] FLAG: --stderrthreshold="2"
I0309 00:48:36.586279       1 flags.go:27] FLAG: --tls-cert-file=""
I0309 00:48:36.586293       1 flags.go:27] FLAG: --tls-cipher-suites="[]"
I0309 00:48:36.586324       1 flags.go:27] FLAG: --tls-min-version=""
I0309 00:48:36.586342       1 flags.go:27] FLAG: --tls-private-key-file=""
I0309 00:48:36.586360       1 flags.go:27] FLAG: --tls-sni-cert-key="[]"
I0309 00:48:36.586383       1 flags.go:27] FLAG: --use-service-account-credentials="false"
I0309 00:48:36.586432       1 flags.go:27] FLAG: --v="2"
I0309 00:48:36.586462       1 flags.go:27] FLAG: --version="false"
I0309 00:48:36.586543       1 flags.go:27] FLAG: --vmodule=""
W0309 00:48:36.586816       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0309 00:48:36.589631       1 authentication.go:55] Authentication is disabled
I0309 00:48:36.589684       1 insecure_serving.go:49] Serving insecurely on [::]:10253
I0309 00:48:36.594197       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/cloud-controller-manager...
I0309 00:48:36.618196       1 leaderelection.go:194] successfully acquired lease kube-system/cloud-controller-manager
I0309 00:48:36.619512       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"cloud-controller-manager", UID:"129e493d-4205-11e9-9daa-02427a3787a5", APIVersion:"v1", ResourceVersion:"626", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' ccm-integration-test-worker_129b3356-4205-11e9-b0a1-0242b996fa24 became leader
I0309 00:48:36.621428       1 node_controller.go:89] Sending events to api server.
I0309 00:48:36.622495       1 pvlcontroller.go:107] Starting PersistentVolumeLabelController
I0309 00:48:36.622522       1 controller_utils.go:1025] Waiting for caches to sync for persistent volume label controller
E0309 00:48:36.623170       1 controllermanager.go:240] Failed to start service controller: the cloud provider does not support external load balancers
I0309 00:48:36.623220       1 controllermanager.go:264] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: true.
E0309 00:48:36.641647       1 connection.go:63] Failed to create govmomi client. err: ServerFaultCode: Login failure
I0309 00:48:36.673085       1 nodemanager.go:114] Discovered VM using normal UUID format
I0309 00:48:36.688189       1 node_controller.go:373] Adding node label from cloud provider: beta.kubernetes.io/instance-type=vsphere-vm
I0309 00:48:36.696186       1 nodemanager.go:114] Discovered VM using normal UUID format
I0309 00:48:36.722832       1 controller_utils.go:1032] Caches are synced for persistent volume label controller
I0309 00:48:36.746236       1 node_controller.go:421] Successfully initialized node ccm-integration-test-control-plane with cloud provider
I0309 00:48:36.750818       1 node_controller.go:373] Adding node label from cloud provider: beta.kubernetes.io/instance-type=vsphere-vm
I0309 00:48:36.790370       1 node_controller.go:421] Successfully initialized node ccm-integration-test-worker with cloud provider
I0309 00:48:36.790546       1 node_controller.go:329] This node ccm-integration-test-control-plane is registered without the cloud taint. Will not process.
I0309 00:48:36.790682       1 node_controller.go:329] This node ccm-integration-test-control-plane is registered without the cloud taint. Will not process.
I0309 00:48:36.790780       1 node_controller.go:329] This node ccm-integration-test-worker is registered without the cloud taint. Will not process.
I0309 00:48:36.792137       1 node_controller.go:329] This node ccm-integration-test-worker is registered without the cloud taint. Will not process.
make[1]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make cluster-down
make[1]: Entering directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
kind delete cluster --name "ccm-integration-test"
Deleting cluster "ccm-integration-test" ...
make[1]: Leaving directory '/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/integration'
```

**Which issue this PR fixes**:
Related to https://github.com/kubernetes/cloud-provider-vsphere/issues/37#issuecomment-470282003

**Special notes for your reviewer**: NA

**Release note**: NA

### CODE REVIEW

**Comment by akutz** [comment]
/hold 

Going to base onto `master`

**Comment by akutz** [comment]
/hold cancel

Actually I'm going to wait to tie this into the main `Makefile`. Please feel free to merge.

**Comment by dvonthenen** [comment]
@akutz is this ok to merge? I think we have 2 lgtms from me and doug?

**Comment by akutz** [comment]
Hi @dvonthenen,

Absolutely. I was going to ping Fabio about this today in fact. I don't want it part of the automated process just yet, but I do want to see it merged so I can iterate on it. Thanks for checking!

**Pull request merged**
